from __future__ import annotations
from typing import Protocol
import pandas as pd

class UiPort(Protocol):
    def set_running(self, running: bool) -> None: ...
    def log(self, message: str) -> None: ...
    def show_error(self, title: str, message: str) -> None: ...
    def set_status(self, text: str) -> None: ...
    def open_validator_window(self) -> None: ...
    def show_dataframe(self, df: pd.DataFrame) -> None: ...
    def enable_export(self, enabled: bool) -> None: ...
    def enable_revalidate(self, enabled: bool) -> None: ...

class UiInputs(Protocol):
    # DB
    def get_db_server(self) -> str: ...
    def get_db_database(self) -> str: ...
    def get_db_user(self) -> str: ...
    def get_db_password(self) -> str: ...
    def get_db_sql(self) -> str: ...
    # API
    def get_api_base_url(self) -> str: ...
    def get_api_role(self) -> str: ...
    def get_api_resource(self) -> str: ...
    def get_api_alias(self) -> str: ...
    def get_api_auth(self) -> str: ...
    def get_api_use_updates(self) -> bool: ...
    def get_api_select(self) -> str: ...
    def get_api_expand(self) -> str: ...
    def get_api_filter(self) -> str: ...
    def get_api_from_date(self) -> str: ...
    def get_api_from_time(self) -> str: ...
    def get_api_to_date(self) -> str: ...
    def get_api_to_time(self) -> str: ...
    # Join
    def get_join_db_key(self) -> str: ...
    def get_join_api_key(self) -> str: ...
    def get_join_how(self) -> str: ...
    def get_join_db_prefix(self) -> str: ...
    def get_join_api_prefix(self) -> str: ...
    def get_validator_script_path(self) -> str: ...
    def get_validate_on_run(self) -> bool: ...
    # Profile/sonstiges
    def get_export_dir(self) -> str: ...
    def get_profile_timezone(self) -> str: ...
    def get_profile_max_rows(self) -> int: ...
    def get_profile_page_cap(self) -> int: ...
    def get_profile_api_timeout(self) -> int: ...
